name: BrainSnob
favicon: null
layout_spectrum: 0.31703345919959247
typography_spectrum: 0.2115026896353811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8658252677414566
  lightness: 0.08200353407301009
  saturation: 0.6407966655679047
  rhythmicContrast: 0.23055278649553657
purpose: []
