name: BrainSnob
favicon: null
layout_spectrum: 0.895
typography_spectrum: 0.65644
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c0000'
    - '#473300'
    - '#6e5b4d'
    - '#d4ad82'
    - '#775100'
  brandStrength: 0.8658252677414566
  lightness: 0.125
  saturation: 0.6407966655679047
  rhythmicContrast: 0.25
purpose: []
